In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
file_path = "reindexed_sessions.csv"

In [3]:
df = pd.read_csv(file_path)

In [4]:
df

,sep,user_id,timestamp,artist_id,artist_name,track_id,track_name
0,1,1,2007-03-01 04:37:37+00:00,f1571db1-c672-4a54-a2cf-aaa329f26f0b,John Frusciante,1,Time Goes Back
1,1,1,2007-03-01 04:39:18+00:00,f1571db1-c672-4a54-a2cf-aaa329f26f0b,John Frusciante,1,Time Goes Back
2,1,1,2007-03-01 04:43:00+00:00,03ad1736-b7c9-412a-b442-82536d63a5c4,Elliott Smith,2,Twilight
3,1,1,2007-03-01 04:45:30+00:00,ff6e677f-91dd-4986-a174-8db0474b1799,Jack Johnson,3,Upside Down
4,1,1,2007-03-01 04:47:15+00:00,ff6e677f-91dd-4986-a174-8db0474b1799,Jack Johnson,3,Upside Down
...,...,...,...,...,...,...,...
23801,1213,177,2008-05-22 00:15:03+00:00,b10bbbfc-cf9e-42e0-be17-e2c3e1d2600d,The Beatles,2722,She Loves You
23802,1213,177,2008-05-22 00:22:12+00:00,de030dcd-36e3-425e-9201-0d5be10769f1,Kill Hannah,3737,Lips Like Morphine
23803,1213,177,2008-05-22 00:25:51+00:00,b10bbbfc-cf9e-42e0-be17-e2c3e1d2600d,The Beatles,2722,She Loves You
23804,1213,177,2008-05-22 00:33:00+00:00,de030dcd-36e3-425e-9201-0d5be10769f1,Kill Hannah,3737,Lips Like Morphine
23805,1213,177,2008-05-22 00:36:39+00:00,b10bbbfc-cf9e-42e0-be17-e2c3e1d2600d,The Beatles,2722,She Loves You